messages = {
    "en": {
        "select_lang": "Please select your language:",
        "lang_set": "Language set successfully! Click Start to begin.",
        "subscribe": "Please subscribe to the required channels to use the bot:",
        "start": "Start",
        "welcome": "Welcome to the Movie Bot!\nYour referral link: {}\nSearch for movies or series below.",
        "search": "Search",
        "help": "Help",
        "about": "About",
        "contact_admin": "Contact Admin",
        "admin_panel": "Admin Panel",
        "search_prompt": "Enter a movie or series name to search",
        "details": "Rating: {rating}\nQuality: {quality}\nYear: {year}\nGenres: {genres}\nDescription: {description}",
        "downloading": "Downloading: {}% (Speed: {:.2f} MB/s)",
        "cancel": "Cancel",
        "download_cancelled": "Download cancelled!",
        "no_download": "No active download to cancel!",
        "episodes": "Episodes",
        "episodes_list": "Select an episode below:",
        "back": "Back",
        "search_results": "Search results for '{}':",
        "points_status": "Daily Points: {}\nReferral Points: {}",
        "no_points": "Insufficient points! Contact @Zaky1million to upgrade to premium or earn more via referrals: {}",
        "premium": "Get Premium",
        "queue_busy": "You already have an active download in the queue!",
        "queue_added": "Added to download queue. Please wait your turn!",
        "help_text": "Use the Search button to find movies or series. Select a result to view details and download options.",
        "about_text": "Movie Bot by @Zaky1million\nVersion 1.0\nEnjoy unlimited movies and series!",
        "referral_bonus": "New user {} joined via your link!\nTotal Referral Points: {}\nDaily Points: {}",
        "check_points": "Check Points",
        "banned": "You are banned from using this bot!",
        "admin_panel_text": "Admin Panel:",
        "add_channel": "Add Subscription Channel",
        "add_premium": "Add Premium User",
        "add_points": "Add Points to User",
        "search_users": "Search Users",
        "banned_users": "Banned Users",
        "enter_channel": "Enter the channel link (e.g., https://t.me/channel):",
        "enter_user_id": "Enter the user ID or username to add as premium:",
        "enter_user_points": "Enter user ID/username and points (e.g., 12345 50):",
        "enter_search_query": "Enter search query for users:",
        "banned_list": "Banned Users:",
        "confirm_unban": "Are you sure you want to unban this user?",
        "yes": "Yes",
        "no": "No",
        "unbanned": "User unbanned successfully!",
        "channel_added": "Channel added successfully!",
        "premium_added": "Premium added to user successfully!",
        "points_added": "Points added to user successfully!",
        "search_results_users": "Search results:",
        "user_not_found": "User not found!",
        "user_info": "User ID: {}\nDaily Points: {}\nReferral Points: {}\nPremium: {}",
        "ban": "Ban User",
        "user_banned": "User banned successfully!",
        "error": "Error: {}"
    },
    "ar": {
        "select_lang": "يرجى اختيار لغتك:",
        "lang_set": "تم تعيين اللغة بنجاح! اضغط على بدء للبدء.",
        "subscribe": "يرجى الاشتراك في القنوات المطلوبة لاستخدام البوت:",
        "start": "بدء",
        "welcome": "مرحبًا بك في بوت الأفلام!\nرابط الإحالة الخاص بك: {}\nابحث عن الأفلام أو المسلسلات أدناه.",
        "search": "بحث",
        "help": "مساعدة",
        "about": "حول",
        "contact_admin": "تواصل مع الإدارة",
        "admin_panel": "لوحة الإدارة",
        "search_prompt": "أدخل اسم فيلم أو مسلسل للبحث",
        "details": "التقييم: {rating}\nالجودة: {quality}\nالسنة: {year}\nالتصنيفات: {genres}\nالوصف: {description}",
        "downloading": "جارٍ التحميل: {}% (السرعة: {:.2f} ميجابايت/ث)",
        "cancel": "إلغاء",
        "download_cancelled": "تم إلغاء التحميل!",
        "no_download": "لا يوجد تحميل نشط لإلغائه!",
        "episodes": "الحلقات",
        "episodes_list": "اختر حلقة أدناه:",
        "back": "رجوع",
        "search_results": "نتائج البحث عن '{}':",
        "points_status": "النقاط اليومية: {}\nنقاط الإحالة: {}",
        "no_points": "النقاط غير كافية! تواصل مع @Zaky1million للترقية إلى المميز أو اربح المزيد عبر الإحالات: {}",
        "premium": "احصل على المميز",
        "queue_busy": "لديك تحميل نشط في قائمة الانتظار بالفعل!",
        "queue_added": "تمت إضافته إلى قائمة التحميل. يرجى الانتظار دورك!",
        "help_text": "استخدم زر البحث للعثور على الأفلام أو المسلسلات. اختر نتيجة لعرض التفاصيل وخيارات التحميل.",
        "about_text": "بوت الأفلام بواسطة @Zaky1million\nالإصدار 1.0\nاستمتع بالأفلام والمسلسلات بدون حدود!",
        "referral_bonus": "انضم مستخدم جديد {} عبر رابطك!\nإجمالي نقاط الإحالة: {}\nالنقاط اليومية: {}",
        "check_points": "تحقق من النقاط",
        "banned": "تم حظرك من استخدام هذا البوت!",
        "admin_panel_text": "لوحة الإدارة:",
        "add_channel": "إضافة قناة اشتراك",
        "add_premium": "إضافة مستخدم مميز",
        "add_points": "إضافة نقاط لمستخدم",
        "search_users": "البحث عن المستخدمين",
        "banned_users": "المستخدمون المحظورون",
        "enter_channel": "أدخل رابط القناة (مثال: https://t.me/channel):",
        "enter_user_id": "أدخل معرف المستخدم أو اسم المستخدم لإضافته كمميز:",
        "enter_user_points": "أدخل معرف المستخدم/اسم المستخدم والنقاط (مثال: 12345 50):",
        "enter_search_query": "أدخل استعلام البحث عن المستخدمين:",
        "banned_list": "قائمة المحظورين:",
        "confirm_unban": "هل أنت متأكد من إلغاء حظر هذا المستخدم؟",
        "yes": "نعم",
        "no": "لا",
        "unbanned": "تم إلغاء حظر المستخدم بنجاح!",
        "channel_added": "تمت إضافة القناة بنجاح!",
        "premium_added": "تمت إضافة المميز للمستخدم بنجاح!",
        "points_added": "تمت إضافة النقاط للمستخدم بنجاح!",
        "search_results_users": "نتائج البحث:",
        "user_not_found": "لم يتم العثور على المستخدم!",
        "user_info": "معرف المستخدم: {}\nالنقاط اليومية: {}\nنقاط الإحالة: {}\nمميز: {}",
        "ban": "حظر المستخدم",
        "user_banned": "تم حظر المستخدم بنجاح!",
        "error": "خطأ: {}"
    }
}
